### ISSUE TITLE
Using stomp with ur5 error

### ISSUE THREAD

**Issue by WwYyFan** [ros-planning/moveit#1113]
### Description

When I using stomp with ur5 , terminal output error
```
[ERROR] [1540203992.012618576]: Number of parameters 6 differs from what was preallocated
[ERROR] [1540203992.012642735]: Failed to generate noisy parameters at iteration 1
```
my stomp_planning.yaml file
```
stomp/manipulator:
  group_name: manipulator
  optimization:
    num_timesteps: 60
    num_iterations: 40
    num_iterations_after_valid: 0
    num_rollouts: 30
    max_rollouts: 30
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST]
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.05, 0.8, 1.0, 0.8, 0.4, 0.4, 0.4]
    cost_functions:
      - class: stomp_moveit/CollisionCheck
        collision_penalty: 1.0
        cost_weight: 1.0
        kernel_window_percentage: 0.2
        longest_valid_joint_move: 0.05
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [255, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/PolynomialSmoother
        poly_order: 6
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.05
        rgb: [0, 191, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
``` 
Can someone tell me how to slove it ?

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
