### ISSUE TITLE
Does Moveit support incrementally built Octomap?

### ISSUE THREAD

**Issue by jacoblim20** [ros-planning/moveit#1188]
I am unable to build an octomap incrementally, by setting "octomap_frame = odom" in husky_ur5_moveit_sensor_manager.launch.xml.

### Your environment
* ROS Distro: [Indigo]
* Ubuntu 14.04
* Binary build 0.7.13-Alpha

### Steps to reproduce
I followed this [perception tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/perception_configuration.html)

### Expected behaviour
Incrementally built octomap when the robot is moved around (as octomap_server)

### Actual behaviour
The octomap seems to be centered on the robot and obstacles are occupying more than one location.
![rviz](https://user-images.githubusercontent.com/44765419/47984502-c4f6c380-e111-11e8-9b65-e3d918a10118.png)

**Comment by simonschmeisser** [comment]
So according to the tutorial the octomap frame should be fixed ie "world_frame" or similar. Your PointCloud/DepthMap should have "odom" (the tf frame of the mobile robot) set as its reference frame.

If you still don't succeed please post more of your config or an example package link.

**Comment by v4hn** [comment]
No feedback, closing.

**Comment by sdfryc-uts** [comment]
I am also experiencing this issue. Setting "octomap_frame = odom" inside the standalone octomap server builds a map as expected.

But setting  "octomap_frame = odom" when configuring the moveit sensor manager launch file seems to have no effect.

- ROS Distro: [kinetic] 
- Ubuntu 16.04

 @simonschmeisser could you please clarify what you mean by "PointCloud/DepthMap should have "odom" (the tf frame of the mobile robot) set as its reference frame (ie in the package header)."?

My sensor configuration is:
```

sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /sensor_d435/depth/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 20.0
    filtered_cloud_topic: filtered_cloud
```


My sensor manager launch file configuration is:

```
<launch>

  <!-- This file makes it easy to include the settings for sensor managers -->

  <!-- Params for 3D sensors config -->
  <rosparam command="load" file="$(find schunk_moveit_config)/config/sensors_3d.yaml" />

  <!-- Params for the octomap monitor -->
  <param name="octomap_frame" type="string" value="odom" />
  <param name="octomap_resolution" type="double" value="0.05" />
  <param name="max_range" type="double" value="5.0" />

  <!-- Load the robot specific sensor manager; this sets the moveit_sensor_manager ROS parameter -->
  <arg name="moveit_sensor_manager" default="mp_700" />
  <include file="$(find schunk_moveit_config)/launch/$(arg moveit_sensor_manager)_moveit_sensor_manager.launch.xml" />

</launch>
```
