### ISSUE TITLE
How to use ros_controllers.yaml ros_controllers.launch from new setup assistant?

### ISSUE THREAD

**Issue by darkdragon-001** [ros-planning/moveit#1314]
In the old moveit_setup_assistant, I had to change the following files:

**controllers.yaml:**
```
controller_list:
 - name: /vel_based_pos_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints: 
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
```

**MYCONFIG_moveit_controller_manager.launch.xml**:
```
<launch>
  <rosparam file="$(find MYCONFIG_moveit_config)/config/controllers.yaml"/>
  <param name="moveit_controller_manager" value="moveit_simple_controller_manager/MoveItSimpleControllerManager"/>
</launch>
```

The new setup assistant generates `ros_controllers.yaml` and `ros_controllers.launch`. How can I include `ros_controllers.launch` from my own launch file?

All tutorials and documentation describe the old interface...

(#894, #951, #994, #908)
