### ISSUE TITLE
PlanningSceneInterface in master seems to ignore header frame and pose

### ISSUE THREAD

**Issue by pbeeson** [ros-planning/moveit#2301]
### Description

In the current MoveIt master branches, there has been added a top level pose for letting multiple meshes and primitive poses be based off another frame's pose, but nowhere in the planning monitor inside moveit is this ever used.

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
source
* If source, which branch?
master

### Steps to reproduce
Call addCollisionObject() in a PlanningSceneInterface, with a CollisionObject that has a frame and a top-level pose.  Then run /get_planning_scene, and you'll ALWAYS get this for the pose:
```
 world: 
    collision_objects: 
      - 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: "world"
        pose: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
```

### Expected behaviour
The pose should be a pose in the frame.  According to the newest move_msgs comments: 
```
# A header, used for interpreting the poses
Header header

# The object's pose relative to the header frame.
# The shapes and subframe poses are defined relative to this pose.
geometry_msgs/Pose pose

......

# The collision geometries associated with the object.
# Their poses are with respect to the object's pose

# Solid geometric primitives
shape_msgs/SolidPrimitive[] primitives
geometry_msgs/Pose[] primitive_poses

# Meshes
shape_msgs/Mesh[] meshes
geometry_msgs/Pose[] mesh_poses
```

### Actual behaviour
The top level pose is basically ignored, and the values set in mesh_poses and primitive_poses are assumed to be directly in the header frame, even if they are not.
