### ISSUE TITLE
Linear Y twist command with MoveIt Servo and 4DoF arm

### ISSUE THREAD

**Issue by dudasdavid** [ros-planning/moveit#2436]
### Description

I'm trying to use the MoveIt Servo with an OpenMANIPULATOR-X which is a 4DoF manipulator from ROBOTIS.
I modified the open_manipulator_controller to listen to the JointTrajectory messages from moveit_servo so communication works properly. When sending linear x or z commands the manipulator works as expected. When sending linear y twist command moveit_servo cannot move the arm. With a 4 DoF manipulator, obviously, I don't expect a clean y translation, but moveit_commander is able to handle such a request in compute_cartesian_path, so I expect a similar behavior here.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Tried both master and melodic-devel branch from source

### Steps to reproduce
You can reproduce the issue using Gazebo.

Use the moveit-servo-experiment branch from my fork for the modified open_manipulator_controller:
https://github.com/dudasdavid/open_manipulator/tree/moveit-servo-expriment

My config file for moveit_servo is:
https://gist.github.com/dudasdavid/61d815a318760cf71f7eb7168a263ed5

- roslaunch open_manipulator_gazebo open_manipulator_gazebo.launch
- roslaunch open_manipulator_controller open_manipulator_controller.launch use_platform:=false use_moveit:=true
- roslaunch moveit_servo spacenav_cpp.launch (without input device)
- send twis command:
```
rostopic pub -r 100 -s /servo_server/delta_twist_cmds geometry_msgs/TwistStamped "header: auto
twist:
  linear:
    x: 0.0
    y: 0.1
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 0.0"
```

### Expected behaviour
Similar behavior as compute_cartesian_path of moveit_commander for a 4DoF manipulator.

### Actual behaviour
X and Z linear twist commands are fine, but Y doesn't work as expected.

**Comment by AndyZe** [comment]
I took a shot at reproducing the issue but got this error upon `roslaunch moveit_servo spacenav_cpp.launch`:

```
ros.rosconsole_bridge.console_bridge: No name given for the robot.
ros.moveit_ros_planning.rdf_loader: Unable to parse URDF from parameter '/robot_description'
```

Do you see any warnings in terminal about singularities? If so, decrease `lower_singularity_threshold` in the yaml.

You can also allow one or more dimensions to "drift" with a service call like this. I would recommend allowing two drift dimensions because the robot is underactuated by 2 DOF. This example will allow small pitch and yaw but should allow very accurate y-translation.

```
rosservice call /servo_server/change_drift_dimensions "drift_x_translation: false
drift_y_translation: false
drift_z_translation: false
drift_x_rotation: false
drift_y_rotation: true
drift_z_rotation: true
transform_jog_frame_to_drift_frame:
  translation: {x: 0.0, y: 0.0, z: 0.0}
  rotation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}"
```
