### ISSUE TITLE
PointCloudOctomapUpdater fails to update the octomap in realtime.

### ISSUE THREAD

**Issue by PatrickVibild** [ros-planning/moveit#2644]
### Description

Delay on octomap generated by PointCloudOctomapUpdater.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04

### Steps to reproduce
Sensor manager.
```
<launch>

  <param name="octomap_frame" type="string" value="odom_combined" />
  <param name="octomap_resolution" type="double" value="0.06" />
  <param name="octomap_latch" type="bool" value="false"/>

  <param name="octomap_sensor_model/min" value="0.99"/>
  <param name="octomap_sensor_model/max" value="0.01"/>

  <param name="octomap_sensor_model/hit" type="double" value="0.99"/>
  <param name="octomap_sensor_model/miss" type="double" value="0.01"/>

  <param name="max_range" type="double" value="5.0" />

  <!-- Load the robot specific sensor manager; this sets the moveit_sensor_manager ROS parameter -->
  <arg name="moveit_sensor_manager" default="edo" />
  <include file="$(find edo_moveit_gripper)/launch/$(arg moveit_sensor_manager)_moveit_sensor_manager.launch.xml" />

</launch>
```

PointCloudOctomapUpdater declaration yaml.

```
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera_side/depth/color/points
    queue_size: 5
    max_range: 3.0
    point_subsample: 1
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.03
    max_update_rate: 5
    filtered_cloud_topic: filtered_cloud
    min_range: 0.3

```

### Expected behaviour
Reading documentation changing the parameters hit/miss and min/max of the sendor_model should make a dynamic octomap.

### Actual behaviour
No changes when modifying the octomap server parameters in the sensor manager. The generated map is not responsive.

**Comment by v4hn** [comment]
I'm not sure you can call this a bug.
The PointCloudOctomapUpdater is definitely very slow, though better hardware helps a bit.

If your point clouds originate from an RGB-D camera, you can accelerate a lot using the [DepthImageOctomapUpdater](https://github.com/ros-planning/moveit/tree/master/moveit_ros/perception/depth_image_octomap_updater) instead.

Integrating a project like [GPU-Voxels](https://gpu-voxels.org/) for faster voxelgrid handling could be very useful, but has not been done ttbomk.

**Comment by PatrickVibild** [comment]
Thanks, I changed the sensor plugin and became way more reactive.

I was wondering if there is anyway defined what are the parameters for each sensor. The documentation is completely empty regarding each of the yaml parameters.


```
        image_topic: This specifies the topic to listen on for a depth image.
        queue_size: he number of images to queue up
        near_clipping_plane_distance:
        far_clipping_plane_distance:
        shadow_threshold:
        padding_offset: The size of the padding (in cm).
        padding_scale:
        filtered_cloud_topic: The topic on which the filtered cloud will be published (mainly for debugging). The filtering cloud is the resultant cloud after self-filtering has been performed.
```
