### ISSUE TITLE
Unexpected behavior from moveit servo

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [ros-planning/moveit#2716]
## Description
Moveit servo not working after recent upgrade to 1.1.5 

## Environment
ROS Distro: [Noetic]
OS Version: Ubuntu 20.04.2
Binary Build
Release: 1.1.5

## Robot  Setup
Unfortunately I cannot share the urdf of the robot I'm using due to the IP restrictions. However, the manipulator is simply a 2R planar arm with a spherical wrist (ZXZ) at the end. 

## Unexpected Behavior 
I had moveit servo working on the binary release (1.1.1) a few months ago. I recently updated to 1.1.5 and I've been getting very odd behavior. Regardless of the input twist command, moveit servo only moves the last joint of the spherical wrist on my manipulator arm (I made sure to move the arm away from any singularities before testing).

Any thoughts on what the issue could be? This is my servo configuration file. `arm_shoulder_link` is the fixed base link
```

###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.6  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.3 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 0.01
low_pass_filter_coeff: 2.  # Larger --> trust the filtered data more, trust the measurements less.

## Properties of outgoing commands
publish_period: 0.005  # 1/Nominal publish rate [seconds]
low_latency_mode: false  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray (for ros_control JointGroupVelocityController or JointGroupPositionController)
# or trajectory_msgs/JointTrajectory (for Universal Robots and other non-ros_control robots)
# command_out_type: trajectory_msgs/JointTrajectory
command_out_type: std_msgs/Float64MultiArray

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: false
publish_joint_velocities: true
publish_joint_accelerations: false

## MoveIt properties
move_group_name:  arm  # Often 'manipulator' or 'arm'
planning_frame: arm_shoulder_link  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: end_effector_link  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  arm_shoulder_link  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  500  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 700 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: status # Publish status to this topic
# command_out_topic: /oil/manipulation/control/peanut_controllers/trajectory_controller/command # Publish outgoing commands here
command_out_topic: /oil/manipulation/control/peanut_controllers/joint_group_velocity_controller/command

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 10 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.05 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]
```
