### ISSUE TITLE
GSoC: Creation of a Benchmark Suite for Evaluating MoveIt Performance

### ISSUE THREAD

**Issue by captain-yoshi** [ros-planning/moveit#2717]
**mentors: @felixvd @mamoll @v4hn**

This issue will bundle all relevant information about the GSoC project. A Discord channel is also available to discuss on this project. I will try to add pertinent information from Discord to this issue.

## Motivation and goals
This GSoC project goal is to benchmark complete tests throughout the entire MoveIt pipeline and eventually the MoveIt Task Constructor (MTC). This will be done through a benchmark suite. Unit tests will also be benchmarked.
- Compare the impact of changes we consider integrating into MoveIt.
- Find regressions between MoveIt versions.
- Isolated tests or benchmarks don't necessarily reflect the entire MoveIt pipeline.
- Some algorithms do well in a particular environment but fall short in other contexts.

#### Phase 1: Exploration and benchmarks (June)
- Create multiple tests with a few scenes (empty scene, solid primitives, meshes, cluttered) with some joint/pose goals, path constraints, FCL and Bullet, planners (OMPL, CHOMP, STOMP) using the `moveit_ros_benchmarks` package.
- Pick and place benchmark using MTC.
- Analyze tests and decide whether we want to use only self contained tests or use and expand the moveit_ros_benchmarks when benchmarking planners throughout the entire MoveIt stack.
- Add an Amazon Pick and Place Challenge (APC) scenario and do benchmarks on it.

#### Phase 2: Creation of the benchmark suite
- Implement the benchmark suite to run tests.
- Aggregate and plot results through Python.
- Add more tests and scenes.

## Documentation
- [Benchmark Tutorial](https://ros-planning.github.io/moveit_tutorials/doc/benchmarking/benchmarking_tutorial.html)
- [Benchmark Visualizer](https://planners-benchmarking.readthedocs.io/en/latest/user_guide/5_visualizing_the_results.html)
- [Planner Arena](http://plannerarena.org/)
## Links
- [Proposal](https://docs.google.com/document/d/10DHBipL6kuHAcFy03jLOLiPuMkW4cKVAcSG4gw6ixBU/edit?usp=sharing)
- GSoC log
- [Discord](https://discord.gg/KzEf7Ysy) #gsoc2021

**Comment by captain-yoshi** [comment]
### Meeting notes 09/06/2021

#### Previous week summary
- Reading + tutorials.
- Create the box and block test (BBT) scenes from [YCB benchmarks](https://www.ycbbenchmarks.com/protocols-and-benchmarks/).

<p align="middle">
<img src="https://user-images.githubusercontent.com/32679594/121739391-85629600-cac9-11eb-9773-fa6e851ea272.png" width="48%" />
  <img src="https://user-images.githubusercontent.com/32679594/121739339-767be380-cac9-11eb-8028-a116da84fb9d.png" width="48%" />
  
</p>

#### Infrastructure
The benchmark suite should have benchmark tests configurable via a yaml file. The objects in the scenes should also be configurable (ex. which object and where). Debate whether we use the moveit_ros_benchmarks for some of the benchmarks or do it manually.

#### Cartesian planner
Benchmark pre-grasp approach between OMPL and Pilz Industrial planner.

#### Execution time
Would it make sense to benchmark the execution of a plan in demo mode (moveit fake controller) or just parse the trajectory to retrieve the trajectory duration?

#### General remarks
- Keep it simple and iterate.
- After the next meeting, we should have a more clearer planning and timeline of the project.
- It is easier to use MTC to select robot states for benchmarking. Moving the interactive markers in RViz is in my opinion difficult in a cluttered scene.
- BBT scene workspace not very restricted. Use something similar to the Amazon picking challenge problem for next scene. Example from @mamoll. 
<p align="center">
<img src="https://user-images.githubusercontent.com/32679594/121740304-e50d7100-caca-11eb-8055-d2dbc6d61ce5.png" alt="drawing" width="200"/>
</p>

#### Next week goals
- Benchmark the BBT scene exhaustively (MoveIt + MTC).
- Create a report with BBT benchmarks as a starting point.
- Create an APC scenario if given enough time.

**Comment by captain-yoshi** [comment]
### Meeting notes 16/06/2021
#### Previous week summary
- Benchmark MTC for pick and place in BBT scenes.
- Benchmark planners with constraints in BBT scenes.
- Explored and tested the moveit_ros_benchmarks package (Constraints + Visualization).
- Sadly the report is not finished yet...
- [PR](https://github.com/ros-planning/moveit_task_constructor/pull/275): Implement missing pregrasp property for RobotState.msg in MTC.
- [PR](https://github.com/ros-planning/moveit/pull/2718): Fix predefined poses benchmark example.

#### MoveIt Benchmark Suite
_This section will refer to some elements of the flowchart (see next comment below)._
**TODO add explanation**


#### Next week goals
- Finish the report with BBT benchmarks.
- Create a scene creator node where one can load collision objects from a configurable yaml file.

**Comment by captain-yoshi** [comment]
### MoveIt Benchmark Suite Flowchart
<p align="center">
<img src="https://user-images.githubusercontent.com/32679594/122293917-83cc1000-cec5-11eb-9073-3ec3969ce9d9.png" alt="drawing"/>
</p>

**Comment by captain-yoshi** [comment]
**MP**
For the Motion Planning pipeline, I think there are only 3 ways to plan a motion:
- `PlanningContext`: solve()
- `PlanningPipeline`: generatePlan()
- `MoveGroupInterface`: plan()

Maybe 5 if you count MoveIt Commander Scripting and the Python MoveGroupInterface.

Is there other functions missing for planning?

**Comment by felixvd** [comment]
Off the top of my head, some PRs for which it would be interesting to evaluate the performance effect (feel free to edit this post to add to the list):

- #2127 
- #2037 
- #2402

**Comment by captain-yoshi** [comment]
### Meeting notes 23/06/2021
#### Previous week summary
- Benchmark [report](https://docs.google.com/spreadsheets/d/1PJA1e7gnr5tJn2Dz6su4CaZtYuYhJHdBqQYETJJPnms/edit?usp=sharing) (plots WIP).
- Benchmarked OMPL, CHOMP and STOMP planners with constraints in BBT scenes (see report).
- Not enough time to start on the scene creator.
- Lots of debugging.
- [PR](https://github.com/ros-industrial/stomp_ros/pull/35): Fix goal position tolerances from box primitive.
- [PR](https://github.com/ros-planning/moveit_resources/pull/86): Floating virtual joint causing weird behaviour.
- [Issue](https://github.com/ros-industrial/stomp_ros/issues/34): Related to previous PR.
- Issue: Fix header comment in `BenchmarkExecutor.h`.
- Issue:
- Issue:
- Issue:
- Issue:
- Issue:
- Issue:
- Issue:


#### MoveIt Benchmark Suite
_This section will refer to some elements of the [flowchart](https://github.com/ros-planning/moveit/issues/2717#issuecomment-862728937)._
The benchmark suite is divided into five sections: **Configuration**, **Pipeline**, **Metric**, **Agregate/Plot** and **Visualisation**.

**Comment by captain-yoshi** [comment]
### Robowflex
Really glad we found this hidden gem called [robowflex](https://github.com/KavrakiLab/robowflex) before the end of GSoC! Essentially it's a benchmark suite and a toolbox (a big wrapper) around MoveIt, Tesseract, Dart and much more. The goals of this library are:
- Provide an easy to use interface to complex robotics libraries by brushing cruft and idiosyncrasies under the rug.
- Provide access to all underlying capabilities of the libraries so users are not hampered by Robowflex in any way.
- Remain untied as possible to the greater ROS system, and support all distros from Kinetic onward.

### Under the hood
Here are my thoughs after playing with it for roughly 10 hours.
- Has very good documentation.
- Good error messages.
- Multiple robots (see [robowflex_resource](https://github.com/KavrakiLab/robowflex_resources)).
- API easy to use and has a lot of examples (script folder).
- IO classes for Rosbag, TF2 Broadcaster, GNUPlot, ROS Paramter Server, Pluginlib, RViz and YAML.
- YAML: Decode and encode for all the essential messages: `geometry_msgs`, `shape_msgs`, `moveit_msgs`, `trajectory_msgs`...
- YAML: Handles the `PlanningScene` Mesh by **package name** or the default vertices soup.
- Live benchmark output to GNUPlot!
- Easy to setup tests programatically.
- Backend for the PlanningPippeline (similary to `moveit_ros_benchmarks`).
- Loads URDF, SRDF, kinematics, limits and planning programatically. This can be loaded from a YAML config.

### What's next?
I think it would make sense to use this library and add GSoC elements to it (STOMP, MTC, Agregate/Plot, Visualization in RViz for debugging trajectories). Of course assuming the author wants these features. So we should have a `moveit_benchmark_suite` that has prepared scenes and benchmarks ready to be executed, unit tests, and meshes for scenes that would depend on robowflex. Well talk about the next steps to take in tomorrows meeting.

@zkingston It would be great to have you're opinion on weather it would make sense to use you're library for benchmarking MoveIt Pipelines and if there are features that you would be interested to have in you're library. Note that this years GSoC is ~17 hours for 10 weeks.

**Comment by captain-yoshi** [comment]
### Creating collision objects
Using YAML one can setup an open shelf in a scene pretty easily. The only downside is that YAML dosen't support math arithmetics (maybe spec 1.3 will add it) so we can't divide by 2 for example or concatenate strings. So there will be hardcoded values. Unless with create special tags that permits these arithmetic's.

We can of course create multiple solid primitives objects (table, shelf, chair) that we can call just like meshes, ex. `ressource: "package://ros_pkg/solid_primitive/shelf.yaml"`. For meshes we should probably have a minimum of 2 subframes: one for the centroid and one at the bottom center of the objects to put it easily on a flat surface. With a certain convention for axes.

Here is a quick example for a shelf and a can. This is just an example, and we should respect somewhat the CollisionObject message like [robowflex](https://github.com/KavrakiLab/robowflex/blob/master/robowflex_library/yaml/test.yml) does it.
```yaml
# YAML anchors
.: &root_frame world

.: &post_dimension
  - 0.035
  - 0.035
  - 1.25

.: &shelf_dimension
  - &dim_x 0.6
  - &dim_y 1.5
  - &dim_z 0.02

.: &shelf_gap 0.25

collision_objects:
  # Open shelf (f=front b=back, l=left, r=right)
  - id: post_bl
    type: box_primitive
    frame_id: *root_frame
    position: [-0.3, -0.75, 0.625]
    dimensions: *post_dimension
  - id: post_br
    type: box_primitive
    frame_id: post_bl
    position: [0.0, *dim_y, 0.0]
    dimensions: *post_dimension
  - id: post_fl
    type: box_primitive
    frame_id: post_bl
    position: [*dim_x, 0.0, 0.0]
    dimensions: *post_dimension
  - id: post_fr
    type: box_primitive
    frame_id: post_br
    position: [*dim_x, 0.0, 0.0]
    dimensions: *post_dimension

  - id: shelf_1
    type: box_primitive
    frame_id: *root_frame
    position: [0.0, 0.0, *shelf_gap]
    dimensions: *shelf_dimension
  - id: shelf_2
    type: box_primitive
    frame_id: shelf_1
    position: [0.0, 0.0, *shelf_gap]
    dimensions: *shelf_dimension
  - id: shelf_3
    type: box_primitive
    frame_id: shelf_2
    position: [0.0, 0.0, *shelf_gap]
    dimensions: *shelf_dimension
  - id: shelf_4
    type: box_primitive
    frame_id: shelf_3
    position: [0.0, 0.0, *shelf_gap]
    dimensions: *shelf_dimension
  - id: shelf_5
    type: box_primitive
    frame_id: shelf_4
    position: [0.0, 0.0, *shelf_gap]
    dimensions: *shelf_dimension

  # Can on the middle shelf
  - id: can
    type: mesh
    resource: "package://ros_pkg/mesh/can.stl"
    scaling: [1.0, 1.0, 1.0]
    frame_id: shelf_3
    position: [0.0, 0.0, -0.025]

```

We could easily create templates of Solid Primitives with Xacro and load them with arguments. I don't know if we want to go that way.
