### ISSUE TITLE
Where is the 'sim_control_mode' parameter that is created by the setup_assistant used?

### ISSUE THREAD

**Issue by rickstaa** [ros-planning/moveit#2837]
### Description

While looking through the code-base of the [moveit_setup_assistant](https://github.com/ros-planning/moveit/tree/master/moveit_setup_assistant) I found the following lines are added to the `ros_controllers.yaml` configuration file:

```yaml
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
  sim_control_mode: 1 # 0: position, 1: velocity
```

These files were added by @MohmadAyman in #894 but I could not find any information about where these parameters are used. I looked in both the [moveit](https://github.com/ros-planning/moveit/), [ros_control](https://github.com/ros-controls/ros_control) and [gazebo_ros_pkgs](https://github.com/ros-simulation/gazebo_ros_pkgs). Does anybody maybe know if these parameters are still required with the latest versions of these packages?

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.4
* Source or Binary build? Source
* If source, which branch? Master
