### ISSUE TITLE
Moveit Servo: Issue getting the moveit servo server pose tracking example to move the  UR5

### ISSUE THREAD

**Issue by stevedanomodolor** [ros-planning/moveit#3004]
Ubuntu 20, moveit ros noetic
I have being trying to get the pose tracking in the moveit servo example  to work but the robot does not seems not to move. The servo server seems to be sending joint position values but for some reason it is not moving(it is not changing value at all, it keeps sending the same joint values). Can someone help me please. 

Also, my joint state node includes other link of the whole robot, is that a problem?
![Screenshot from 2021-12-18 13-02-11](https://user-images.githubusercontent.com/61468301/146640289-1053342b-06ff-4708-aa07-30bd74d42c80.png)

controller screen
![Screenshot from 2021-12-18 13-09-25](https://user-images.githubusercontent.com/61468301/146640480-a5c151b7-2141-43b4-a9e9-47196edb3e83.png)

I am using the pose_tracking example and my launch file is 

I added a marker to see the goal in the pose_tracking example code 
```

  target_pose.pose.orientation = current_ee_tf.transform.rotation;
  ROS_INFO("Pose: %f %f %f",target_pose.pose.position.x,target_pose.pose.position.y,target_pose.pose.position.z );

  // Modify it a little bit
  target_pose.pose.position.x -= 0.1;
  target_pose.pose.position.z -= 0.1;

  // resetTargetPose() can be used to clear the target pose and wait for a new one, e.g. when moving between multiple
  // waypoints
  tracker.resetTargetPose();

  // Publish target pose
  target_pose.header.stamp = ros::Time::now();
  target_pose_pub.publish(target_pose);

  // Run the pose tracking in a new thread
  std::thread move_to_pose_thread(
      [&tracker, &lin_tol, &rot_tol] { tracker.moveToPose(lin_tol, rot_tol, 0.1 /* target pose timeout */); });
      visualization_msgs::Marker marker;
      marker.header.frame_id = "ur5_arm_base_link";
      marker.header.stamp = ros::Time();
      marker.ns = "my_namespace";
      marker.id = 0;
      marker.type = visualization_msgs::Marker::SPHERE;
      marker.action = visualization_msgs::Marker::ADD;
      marker.pose.position= target_pose.pose.position;
      marker.pose.orientation.x = 0.0;
      marker.pose.orientation.y = 0.0;
      marker.pose.orientation.z = 0.0;
      marker.pose.orientation.w = 1.0;
      marker.scale.x = 0.1;
      marker.scale.y = 0.1;
      marker.scale.z = 0.1;
      marker.color.a = 1.0; // Don't forget to set the alpha!
      marker.color.r = 0.0;
      marker.color.g = 1.0;
      marker.color.b = 0.0;
      //only if using a MESH_RESOURCE marker type:
  ros::Rate loop_rate(50);
  for (size_t i = 0; i < 6; ++i)
  while(ros::ok())
  {
    // Modify the pose target a little bit each cycle
    // This is a dynamic pose target
    // target_pose.pose.position.z -= 0.04;
    target_pose.header.stamp = ros::Time::now();
    tracker.getCommandFrameTransform(current_ee_tf);
    ROS_INFO("Pose: %f %f",target_pose.pose.position.z, current_ee_tf.transform.translation.z );

    target_pose_pub.publish(target_pose);
    vis_pub.publish( marker );

    loop_rate.sleep();
  }
```

```
###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: true # Whether the robot is started in a Gazebo simulation environment
target_control_rate: 50 # [Hz] Control rate

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.03 # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.06 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 0.1
low_pass_filter_coeff: 2.  # Larger --> trust the filtered data more, trust the measurements less.

## Properties of outgoing commands
publish_period: 0.01  # 1/Nominal publish rate [seconds]
low_latency_mode: false  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray (for ros_control JointGroupVelocityController or JointGroupPositionController)
# or trajectory_msgs/JointTrajectory (for Universal Robots and other non-ros_control robots)
command_out_type: std_msgs/Float64MultiArray

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## MoveIt properties
move_group_name:  ur5_arm  # Often 'manipulator' or 'arm'
planning_frame: ur5_arm_base_link  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: ur5_arm_ee_link  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  ur5_arm_ee_link  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout: 1000000 # 0.1  Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 5

## Configure handling of singularities and joint limits
lower_singularity_threshold:  50  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 300 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_state
status_topic: /servo/status # Publish status to this topic
command_out_topic: /ur5_joint_group_position_controller/command # Publish outgoing commands here

## Collision checking for the entire robot body
check_collisions: false # Check collisions?
collision_check_rate: 5 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: stop_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.03 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]

```

launch file 

```
<launch>
  <!-- Launch an example that sends commands via C++ API. -->
  <include file="$(find husky_ur5_robotiq_85_moveit_config)/launch/planning_context.launch" >
    <arg name="load_robot_description" value="true"/>
  </include>


  <node name="servo_server" pkg="moveit_servo" type="pose_tracking_example" output="screen" >
    <!-- <param name="parameter_ns" type="string" value="servo_server" /> -->
    <rosparam command="load" file="$(find moveit_servo)/config/ur_simulated_config.yaml" />
    <rosparam command="load" file="$(find moveit_servo)/config/pose_tracking_settings.yaml" />
  </node>

</launch>


```

I made sure that indeed the servo server is publish to the jointgroup command and it indeed is. 
```
 dim: []
  data_offset: 0
data: [8.317409593127495e-05, -1.0746929722850296, -1.7784759029924857, 0.03235928375662292, 1.5668587059545473, 3.10714525626066e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.317054743778654e-05, -1.0746929176999998, -1.7784758827350156, 0.03235928787545515, 1.5668587051904208, 3.107092533564156e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.314201753307319e-05, -1.0746924816851837, -1.7784757187501885, 0.032359320498964436, 1.5668586992062716, 3.106675897576433e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.310657985542233e-05, -1.0746919389547367, -1.7784755152522913, 0.032359361132635184, 1.5668586917185108, 3.10615645170154e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.309618666034284e-05, -1.0746917784722183, -1.7784754558157083, 0.03235937318579456, 1.5668586894589862, 3.106001797619814e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.309272226198302e-05, -1.0746917249780457, -1.778475436003514, 0.032359377203514346, 1.5668586887058114, 3.105950246259238e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.30648207120632e-05, -1.0746912979184353, -1.7784752755498243, 0.03235940921101469, 1.566858682875699, 3.105541931650686e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.303016165234128e-05, -1.0746907663447325, -1.7784750764314587, 0.032359449084734995, 1.5668586755832479, 3.105032825820753e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.301999683981853e-05, -1.074690609161218, -1.778475018274492, 0.0323594609122682, 1.5668586733824048, 3.1048812537387205e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.301660856897762e-05, -1.0746905567667133, -1.7784749988888366, 0.032359464854779266, 1.5668586726487903, 3.1048307297113765e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.29893619981862e-05, -1.0746901384375707, -1.7784748417726175, 0.032359496130022695, 1.5668586668735227, 3.104431279819935e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.295551819096341e-05, -1.0746896177290917, -1.7784746467915244, 0.032359535086436256, 1.5668586596464134, 3.10393325912004e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.294559245210796e-05, -1.074689463758475, -1.7784745898431407, 0.03235954664216678, 1.5668586574660868, 3.103784990032988e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.291678767784574e-05, -1.074689019364139, -1.7784744234768723, 0.03235957989445985, 1.5668586513808638, 3.103362189679347e-05]
---
layout: 
  dim: []
  data_offset: 0
data: [8.287851060011768e-05, -1.0746884174879834, -1.7784741993958133, 0.032359623776948114, 1.5668586426327273, 3.102763610824782e-05]
---

```

 controller yaml file
```
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125

# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: robotiq_85_left_knuckle_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

# Trajectory controller
ur5_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5_arm_shoulder_pan_joint
    - ur5_arm_shoulder_lift_joint
    - ur5_arm_elbow_joint
    - ur5_arm_wrist_1_joint
    - ur5_arm_wrist_2_joint
    - ur5_arm_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    ur5_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    ur5_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    ur5_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
    ur5_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    ur5_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    ur5_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
ur5_joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - ur5_arm_shoulder_pan_joint
     - ur5_arm_shoulder_lift_joint
     - ur5_arm_elbow_joint
     - ur5_arm_wrist_1_joint
     - ur5_arm_wrist_2_joint
     - ur5_arm_wrist_3_joint
# /gazebo_ros_control:
#     pid_gains:
#       ur5_arm_shoulder_pan_joint: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
#       ur5_arm_shoulder_lift_joint: {p: 500.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0}
#       ur5_arm_elbow_joint: {p: 10000.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
#       ur5_arm_wrist_1_joint: {p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -400.0, i_clamp_max: 400.0}
#       ur5_arm_wrist_2_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
#       ur5_arm_wrist_3_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

#
/gazebo_ros_control:
    pid_gains:
      ur5_arm_shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
      ur5_arm_shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10.0}
      ur5_arm_elbow_joint: {p: 100.0, i: 0.01, d: 10.0}
      ur5_arm_wrist_1_joint: {p: 200.0, i: 100.01, d: 10.0}
      ur5_arm_wrist_2_joint: {p: 100.0, i: 0.01, d: 10.0}
      ur5_arm_wrist_3_joint: {p: 100.0, i: 0.01, d: 10.0}

```

launch file gazebo
```

<?xml version="1.0"?>
<launch>
<!--
  <env name="GAZEBO_MODEL_PATH"
       value="$(find husky_ur5_robotiq_85)/models:$(optenv GAZEBO_MODEL_PATH)" /> -->

  <!-- Launch file parameters -->
  <arg name="paused"     default="true"/>
  <arg name="debug"      default="false"/>
  <arg name="gui"        default="true"/>
  <arg name="rate"       default="125" />
  <!-- <arg name="world_name" default="$(find husky_ur5_robotiq_85)/worlds/ur5_world_setup.world" /> -->

  <!-- Start up simulated world -->
  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <!-- <arg name="world_name" value="$(arg world_name)"/> -->
    <arg name="paused"     value="$(arg paused)"/>
    <arg name="debug"      value="$(arg debug)"/>
    <arg name="gui"        value="$(arg gui)"/>
  </include>

  <!-- Send robot urdf to param server -->
  <param name="robot_description" command="$(find xacro)/xacro --inorder '$(find husky_ur5_robotiq_85)/urdf/husky_ur5_robotiq85_gripper.urdf.xacro'" />
  <!-- Spawn robot in gazebo (and move it upwards):
       better initial values should be -2.355 and 1.57 but the robot does
       something strange when unpausing it
  -->
  <node name="spawn_gazebo_model" pkg="gazebo_ros" type="spawn_model"
        args="-urdf -param robot_description -model ur5_husky_robotiq_85f
              -J ur5_arm_shoulder_lift_joint -1.1
              -J ur5_arm_elbow_joint -1.57
              -J ur5_arm_wrist_2_joint 1.57"
        output="screen" />

  <!-- <include file="$(find husky_ur5_robotiq_85)/launch/husky_ur5_robotiq_85f_controller.launch" /> -->

  <rosparam file="$(find husky_ur5_robotiq_85)/config/husky_controller.yaml" command="load" />
  <rosparam file="$(find husky_ur5_robotiq_85)/config/ur5_robotiq_85_controller.yaml" command="load" />
  <node name="ros_control_controller_manager" pkg="controller_manager" type="spawner" respawn="false" output="screen" args=" joint_state_controller ur5_joint_group_position_controller gripper_controller" />
  <node name="ros_control_controller_manager1" pkg="controller_manager" type="controller_manager" respawn="false" output="screen" args="load ur5_trajectory_controller  " />
  <node name="base_controller_spawner" pkg="controller_manager" type="spawner" args="husky_joint_publisher husky_velocity_controller"/>
  <!-- TF -->
  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency"  type="double" value="50" />
  </node>

  <!-- <node type="rviz" name="rviz" pkg="rviz" args="-d $(find husky_ur5_robotiq_85)/rviz/husky_ur5_robotiq_85.rviz" /> -->
</launch>


```
