### ISSUE TITLE
MotionPlanning RViz plugin have to be manually refreshed after clear_octomap

### ISSUE THREAD

**Issue by FSund** [ros-planning/moveit#3045]
### Description

After calling the `/clear_octomap` service, the MotionPlanning RViz plugin have to be reloaded (uncheck and re-check the plugin, or remove/add), for the octomap to disappear from the Planning Scene.

The same happens if an **empty** octomap is loaded from a file via `/move_group/load_map` (the old octomap is still shown until the plugin is reloaded). The empty map is generated via `/move_group/save_map` on a fresh scene.

The same behaviour is present when calling the `/apply_planning_scene` service with an empty octomap:
(untested code, it is a minimal version of the actual code I use)
```
get_planning_scene = rospy.ServiceProxy('/get_planning_scene', GetPlanningScene)
components = PlanningSceneComponents()
components.components = sum([
    PlanningSceneComponents.WORLD_OBJECT_NAMES,
    PlanningSceneComponents.WORLD_OBJECT_GEOMETRY,
    PlanningSceneComponents.OCTOMAP
])
ps = get_planning_scene(components)
ps = ps.scene  # moveit_msgs/PlanningScene
ps.is_diff = True
ps.world.octomap = OctomapWithPose()
apply_planning_scene = rospy.ServiceProxy('/apply_planning_scene', ApplyPlanningScene)
apply_planning_scene(ps)
```

I am not sure if any of these 3 methods of clearing the octomap are related, but I thought I'd just as well report all the similar issues I've run into.

### Your environment
* ROS Distro: Noetic
* OS Version: Pop!OS
* Built from source, branch `master` (moveit repo is on commit e7b388d238159de020a9c31f5896112c1513bf6b)
* The behaviour seems to be the same on moveit 1.1.7 from apt on Pop!OS 20.04

### Steps to reproduce
- Start RViz and moveit
- Load/scan any octomap
- Call service `/clear_octomap`

### Expected behaviour
I would expect the octomap to disappear from the Planning Scene after the service is called.

### Actual behaviour
The octomap is still shown until I reload the MotionPlanning plugin.

**Comment by atmagopal** [comment]
I've been experiencing the same issue. Have you had any progress towards fixing this @FSund ?

**Comment by v4hn** [comment]
Quickly skimming the code clearing the octomap should trigger `UPDATE_GEOMETRY` which *should* trigger publishing a new ROS message with the cleared octomap. Can you see the message on the `move_group/monitored_planning_scene` topic when you clear the scene?
Either the trigger fails or the new message is interpreted wrongly in the RViz plugin.

**Comment by FSund** [comment]
> Can you see the message on the `move_group/monitored_planning_scene` topic when you clear the scene?

Yes, the following message appears on the `monitoried_planning_scene` topic when I press "Clear octomap" in RViz

```
---
name: "(noname)+"
robot_state: 
[...]
world: 
  collision_objects: []
  octomap: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "ab_base"
    origin: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
    octomap: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      binary: False
      id: ''
      resolution: 0.0
      data: []
is_diff: True
---
```

The Octomap is still visible in RViz though.
