### ISSUE TITLE
moveit_servo commands published indefinitely with stale nonzero twist command

### ISSUE THREAD

**Issue by playertr** [ros-planning/moveit#3049]
### Description

I've noticed that (with my configuration), when the last Twist command issued`/servo_server/delta_twist_cmds` is nonzero, the servo server _never_ stops publishing JointTrajectory commands to `command_out_topic`, even when that last message is stale.

I'm not sure if that behavior is intended: it surprised me that the `incoming_command_timeout` parameter caused JointTrajectory outputs to stop being published only if the last command was zero.

Specifically, this threw me for a loop because I have a system that uses proportional control for visual servoing, and terminates when the end effector pose is within a threshold distance (resulting in a nonzero final servo Twist command). The presence of continued non-motion-causing JointTrajectory commands from the servo server was preempting execution of MoveIt plans later in my script.

Is this a bug?

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source build from 920eae6742cc5af2349349a2eac57d5a19bee7f5

<details> 
<summary> panda_moveit_servo.yaml  </summary>

```
###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment
# this is disabled because it led to jerkiness and interacted poorly with the LPF

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.6  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.3 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 1.0

# smoothing_filter_plugin_name:
low_pass_filter_coeff: 1.0  # Larger --> trust the filtered data more, trust the measurements less.

## Properties of outgoing commands
publish_period: 0.02  # 1/Nominal publish rate [seconds]
low_latency_mode: false  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray (for ros_control JointGroupVelocityController or JointGroupPositionController)
# or trajectory_msgs/JointTrajectory (for Universal Robots and other non-ros_control robots)
# command_out_type: std_msgs/Float64MultiArray
command_out_type: trajectory_msgs/JointTrajectory

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## MoveIt properties
move_group_name: panda_arm  # Often 'manipulator' or 'arm'
planning_frame: panda_link0  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: panda_hand  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  panda_link0  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold: 70.0  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 100.0 # Stop when the condition number hits this
joint_limit_margin: 0.05 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: status # Publish status to this topic
# command_out_topic: /joint_group_position_controller/command # Publish outgoing commands here
command_out_topic: /panda_arm_controller/command

## Collision checking for the entire robot body
check_collisions: false # Check collisions?
collision_check_rate: 10.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.03 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.0 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 10.0 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]

```

</details> 

### Steps to reproduce

1. Bring up a working servo server with a robot arm.
2. Issue nonzero Twist commands to the servo server. Observe that output JointTrajectories (or Float64MultiArrays) are published.
3. Stop issuing those Twist commands, without first issuing a zero Twist command. Observe that non-motion-causing outputs continue to be published even after `incoming_command_timeout` has passed.

After completing these steps, I've found that issuing a zero Twist command causes the outputs to stop being published.

I'm happy to provide a minimal example in a Docker container, but I'm primarily seeking input on whether this behavior is intended.

### Expected behaviour
I would expect that, after the nonzero Twist commands expire, JointTrajectory outputs would stop being issued.

### Actual behaviour
JointTrajectory outputs continue being issued if the last Twist command was nonzero. However, these JointTrajectory outputs are non-motion-causing.
