### ISSUE TITLE
Can I fix demo_gazebo.launch generated by moveit_setup_assistant? 

### ISSUE THREAD

**Issue by AzulRadio** [ros-planning/moveit#3058]
Environment: Ubuntu 20.04, noetic, moveit: 1.1.8-1focal.20220212.181457 from binary.

When I generate the moveit config package from a .xacro file with moveit_setup_assistant, the generated demo_gazebo.launch is broken. I ran into the same issue as #2210 and #2237 where the robot moves in Rviz but not in Gazebo. With Error msg: 
```
Unable to identify any set of controllers that can actuate the specified joints
```

I looked into this and found that the solution is quite simple (at least for me): append 
```
controller_list:
  - name: <controller_name>
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - <joint_name>
```
at the end of `ros_controller.yaml` is sufficient (at least for me) to solve the problem.
(credit:  **venkys** from https://answers.ros.org/question/320990/moveit-unable-to-identify-any-set-of-controllers/)

This bug is too trivial (but cost me 2 weeks to find) and I think maybe I can fix it. But since the 2 issues I mentioned above are all quite old and both closed, I decided to ask before making a PR: **is this a bug already fixed/in fixing? also, is it an appropriate fix?** (well, it seems to be a workaround)

Thanks for your help!
