### ISSUE TITLE
Perception by using gazebo kinect sensor error

### ISSUE THREAD

**Issue by sm3304love** [ros-planning/moveit#3062]
## Background

I tried to detect collision using the point cloud received from the kinect sensor created using the GAZEBO plug-in. Following the moveit tutorial, I modified sensors_kinect_pointcloud.yaml as below, and also modified sensor_manager.launch.xml as below. But I get a Transform error.

sensors_kinect_pointcloude.yaml
```
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /depth/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
```

sensor_manager.launch.xml
```
<launch>

  <!-- This file makes it easy to include the settings for sensor managers -->


 <!-- kinect_pointcloude -->
  <rosparam command="load" file="$(find panda_moveit_config)/config/sensors_kinect_pointcloud.yaml" />


  <!-- Params for the octomap monitor -->
  <param name="octomap_frame" type="string" value="world" />
  <param name="octomap_resolution" type="double" value="0.025" />
  <param name="max_range" type="double" value="5.0" />

  <!-- Load the robot specific sensor manager; this sets the moveit_sensor_manager ROS parameter -->
  <arg name="moveit_sensor_manager" default="panda" />


  <!-- octomap  -->
<param name="octomap_frame" type="string" value="odom_combined" />
<param name="octomap_resolution" type="double" value="0.05" />
<param name="max_range" type="double" value="5.0" />

</launch>
```

Your environment
* ROS Distro: Noetic
* OS Version:Ubuntu 20.04

### Steps to reproduce
Create a panda_moveit_config file using moveit setup assistant, and create a kinect sensor in gazebo. And modify sensors_kinect_pointcloude.yaml to receive pointcloude topic from gazebo's kinect. After that, modify sensor_manager.launch.xml and run demo_gazebo.launch.

The error occurs immediately when creating a kinect sensor in a gazebo.

### Expected behaviour
Tell us what should happe
Performing collision avoidance using the kinect sensor created in gazebo

### Actual behaviour
Tell us what happens instead
![Screenshot from 2022-02-17 21-23-25](https://user-images.githubusercontent.com/57741032/154483008-fd3cb652-455f-4383-90d1-5ae8cd221d78.png)

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.
