### ISSUE TITLE
MotionPlanning plugin needs to be manually refreshed in Noetic

### ISSUE THREAD

**Issue by mostlyjason** [ros-planning/moveit#3070]
### Description

When I load the MotionPlanning plugin in Rviz, several tabs have boxes which refuse to update or paint.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04 using x11
* Source or Binary build? binary
* If binary, which release version? Docker. Not sure how tell which version, but I see libmoveit_planning_scene_rviz_plugin_core.so.1.1.8 in my binaries.
* Using Nvidia base image `nvidia/opengl:1.1-glvnd-runtime-ubuntu20.04` and `osrf/ros:noetic-desktop-full`

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

Docker-compose:
```
version: '3.4'

x-app: &common
  command: [ "roslaunch ${LAUNCH_TARGET} --screen -v" ]
  privileged: true
  environment:
    PYTHONUNBUFFERED: 1
    QT_X11_NO_MITSHM: 1
    DISPLAY: $DISPLAY
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  build:
    context: .
    args: &common-args
      ROS_DISTRO: "noetic"
      BASE_IMAGE: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04

services:
  # This configuration builds the project for computers with NVIDIA hardware
  nvidia-ros: 
    <<: *common
    runtime: nvidia
```

Dockerfile:
```
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
COPY --from=osrf/ros:noetic-desktop-full / /
ENV BASH_ENV="/root/launch.sh"
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash", "-c"]
ENV ROS_DISTRO="noetic"
RUN echo "source /opt/ros/noetic/setup.bash" >> $BASH_ENV

# Install build dependencies
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y \
        # ROS Build dependencies
        python3-rosinstall \
        python3-rosinstall-generator \
        python3-wstool \
        build-essential \
        ros-noetic-catkin \
        python3-catkin-tools \
        ros-noetic-moveit \
        python3-pip \
        ros-noetic-realsense2-camera \
        ros-noetic-realsense2-description \
        ros-noetic-find-object-2d \
        ros-noetic-object-recognition-msgs \
        libcanberra-gtk-module \
        libcanberra-gtk3-module

# Project-specific build dependencies
RUN rosdep install -r -y -i --from-paths . && \
    rm -rf /var/lib/apt/lists/*

# Build the project
WORKDIR /catkin_ws
```

### Expected behaviour
It should paint the contents of the entire tab when switching tabs.

### Actual behaviour
The Planning tab seems to work fine. However, if I select the Scene Objects tab, the contents of the current scene objects does not update. Instead, it displays the contents of the Joints tab. The same thing happens for several other tabs. I can also force it to paint the contents of the screen by manually removing the reloading the plugin. However, when I interact with the UI it doesn't update the contents unless I manually reload the plugin. This only happens on Noetic. When I run Melodic all the tabs work fine. 

See Current Scene objects box:
![image](https://user-images.githubusercontent.com/6370704/155898693-455971c3-1da6-45bc-b2d4-b6642ed65971.png)

See Planner parameters box:
![image](https://user-images.githubusercontent.com/6370704/155898727-18648248-5fa2-4a83-a5bb-a81ebf8d7c18.png)

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

I don't see any useful logs in the console output
