### ISSUE TITLE
[moveit_servo] Questions about servo implementation

### ISSUE THREAD

**Issue by erencandural** [ros-planning/moveit#3114]
### Description
Hello everyone, I'm trying to get the `pose_tracking_example` to work on Franka Emika Panda using MoveIt! 1 for a teleoperation project. I'm trying to subscribe to TwistStamped messages but I've been encountering the error 

> Target control rate was missed.

- I'm sending the TwistStamped messages from Unity (in Windows) to ROS which is running in a virtual machine (Ubuntu).
- I have no problem publishing the TwistStamped messages from Unity as I've checked with `rostopic echo /cube_twist_stamped`. (this is the topic name I'm using)
- I'm also subscribing to `/joint_states` on Unity to visualize the robot there as well.
- I'm using the workspace created with the MoveIt! tutorials and I'm using the command `roslaunch panda_moveit_config demo.launch` to launch RViz.

### Environment
(I don't know if me working on a virtual machine makes a difference but here are the details just in case)
- Host OS: Windows 10
- Virtual Machine OS: Ubuntu 20.04 LTS
- ROS Distro: Noetic
- Robot: Franka Emika Panda

### Result
```
roslaunch moveit_servo panda_pose_tracking_example.launch
... logging to /home/erencan/.ros/log/ac2e8274-b76f-11ec-9857-538263d8cff1/roslaunch-erencan-VirtualBox-2831.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://erencan-VirtualBox:40987/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /servo_server/angular_derivative_gain: 0.0
 * /servo_server/angular_integral_gain: 0.0
 * /servo_server/angular_proportional_gain: 0.5
 * /servo_server/cartesian_command_in_topic: /cube_twist_stamped
 * /servo_server/check_collisions: True
 * /servo_server/collision_check_rate: 50.0
 * /servo_server/collision_check_type: threshold_distance
 * /servo_server/collision_distance_safety_factor: 1000.0
 * /servo_server/command_in_type: speed_units
 * /servo_server/command_out_topic: /robot_state_publ...
 * /servo_server/command_out_type: std_msgs/Float64M...
 * /servo_server/ee_frame_name: panda_link8
 * /servo_server/hard_stop_singularity_threshold: 30.0
 * /servo_server/incoming_command_timeout: 100
 * /servo_server/joint_command_in_topic: /delta_joint_cmds
 * /servo_server/joint_limit_margin: 0.1
 * /servo_server/joint_topic: /joint_states
 * /servo_server/low_latency_mode: True
 * /servo_server/low_pass_filter_coeff: 2.0
 * /servo_server/lower_singularity_threshold: 17.0
 * /servo_server/min_allowable_collision_distance: 0.01
 * /servo_server/move_group_name: panda_arm
 * /servo_server/num_outgoing_halt_msgs_to_publish: 4
 * /servo_server/planning_frame: panda_link0
 * /servo_server/publish_joint_accelerations: False
 * /servo_server/publish_joint_positions: True
 * /servo_server/publish_joint_velocities: False
 * /servo_server/publish_period: 0.02
 * /servo_server/robot_link_command_frame: panda_link0
 * /servo_server/scale/joint: 0.01
 * /servo_server/scale/linear: 0.6
 * /servo_server/scale/rotational: 0.3
 * /servo_server/scene_collision_proximity_threshold: 0.02
 * /servo_server/self_collision_proximity_threshold: 0.01
 * /servo_server/status_topic: /status
 * /servo_server/use_gazebo: False
 * /servo_server/windup_limit: 0.05
 * /servo_server/x_derivative_gain: 0.0
 * /servo_server/x_integral_gain: 0.0
 * /servo_server/x_proportional_gain: 1.5
 * /servo_server/y_derivative_gain: 0.0
 * /servo_server/y_integral_gain: 0.0
 * /servo_server/y_proportional_gain: 1.5
 * /servo_server/z_derivative_gain: 0.0
 * /servo_server/z_integral_gain: 0.0
 * /servo_server/z_proportional_gain: 1.5

NODES
  /
    servo_server (moveit_servo/pose_tracking_example)

ROS_MASTER_URI=http://localhost:11311

process[servo_server-1]: started with pid [2845]
[ INFO] [1649445099.420303031]: Loading robot model 'panda'...
[ WARN] [1649445099.421166439]: Link panda_leftfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1649445099.421212699]: Link panda_rightfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ INFO] [1649445099.504575079]: Starting planning scene monitor
[ INFO] [1649445099.505993970]: Listening to '/planning_scene'
[ INFO] [1649445099.506019338]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1649445099.507288892]: Listening to '/collision_object'
[ INFO] [1649445099.508752350]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1649445099.511479031]: Listening to '/attached_collision_object' for attached collision objects
[ WARN] [1649445109.772096150]: Target control rate was missed
[ INFO] [1649445119.773294957]: Halting servo motion, a stop was requested.
[ INFO] [1649445119.781840726]: Stopping world geometry monitor
[ INFO] [1649445119.782345533]: Stopping planning scene monitor
[servo_server-1] process has finished cleanly
log file: /home/erencan/.ros/log/ac2e8274-b76f-11ec-9857-538263d8cff1/servo_server-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

### Problem
I know from having looked at other issues in this repo and also the main code of the example that there should be other checkpoints after `Listening to '/attached_collision_object' for attached collision objects` like obtaining the first pose so I think but I don't know where I'm wrong. I couldn't find something elaborative enough for this specific example and I wanted to ask help about how my approach is wrong.

### Config File
I've only changed the original `ur_simulated_config.yaml` a little for the Franka Emika Panda Robot. From what I've seen in previous topics using the same robot, I seem to be on the right track as far as parameters are concerned but I'm not entirely sure.
```
###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.6  # Max linear velocity. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.3 # Max angular velocity. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Only used for joint commands on joint_command_in_topic.
  joint: 0.01
low_pass_filter_coeff: 2.  # Larger --> trust the filtered data more, trust the measurements less.

## Properties of outgoing commands
publish_period: 0.02  # 1/Nominal publish rate [seconds]
low_latency_mode: true  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray or trajectory_msgs/JointTrajectory
command_out_type: std_msgs/Float64MultiArray

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## MoveIt properties
move_group_name:  panda_arm  # Often 'manipulator' or 'arm'
planning_frame: panda_link0  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: panda_link8  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  panda_link0  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  100  # Stop servoing if X seconds elapse without a new command (it was 0.1 originally)
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  17.0  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 30.0 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: /cube_twist_stamped  # Topic for incoming Cartesian twist commands
joint_command_in_topic: /delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: /status # Publish status to this topic
command_out_topic: /robot_state_publisher # Publish outgoing commands here

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 50.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.02 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000.0 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]
```
### Node Graph
Here is the node graph I'm obtaining before the servo server stops. The node `/rosbridge_websocket` is what's enabling the connection between Unity in Windows and ROS in the Ubuntu running in the virtual machine.
![panda servo rosgraph](https://user-images.githubusercontent.com/47418871/162514854-33def05d-6f9f-48e7-8cc0-0af7a8e0801c.png)
