### ISSUE TITLE
How do I control the speed of a real robot with MoveIt  ( in ComputecartesianPath) ?

### ISSUE THREAD

**Issue by AtariaLee** [ros-planning/moveit#3117]
I had control a real robot(fanuc m710ic_50) with Moveit. And i created a plan path using  `computeCartesianPath` , its worked in my robot. But the robot moves too slowly ,so i  tried to speed up my robot.  I changed some parameters using`arm.setMaxVelocityScalingFactor(0.6)` and ` arm.setMaxAccelerationScalingFactor(0.4)` ,but it didnt work. 
Then I created a function to try to redefine the parameters in my plan path, like
```
 void scale_trajectory_speed(moveit::planning_interface::MoveGroupInterface::Plan &plan, double scale)

    {
        int n_joints = plan.trajectory_.joint_trajectory.joint_names.size();
        
        for(int i=0; i<plan.trajectory_.joint_trajectory.points.size(); i++)
        {
            plan.trajectory_.joint_trajectory.points[i].time_from_start *= 1/scale;
            
            for(int j=0; j<n_joints; j++)
            {
                plan.trajectory_.joint_trajectory.points[i].velocities[j] *= scale;
                plan.trajectory_.joint_trajectory.points[i].accelerations[j] *= scale*scale;
            }
        }
    }
```
unfortunately, it didt work too .So how could i control the speed of realrobot with Moveit (using computeCartesianPath)?
Thanks for everyones help!

**Comment by AtariaLee** [comment]
Then i tried to use `trajectory_processing::IterativeParabolicTimeParameterization::computeTimeStamps` to change time scale,like 

    moveit::planning_interface::MoveGroupInterface::Plan plan;

    robot_trajectory::RobotTrajectory rt(arm.getCurrentState()->getRobotModel(),"manipulator");

    rt.setRobotTrajectoryMsg(*arm.getCurrentState(),trajectory);
    trajectory_processing::IterativeParabolicTimeParameterization iptp;
    bool ItSuccess = iptp.computeTimeStamps(rt);
    ROS_INFO("Computed time stamp %s", ItSuccess ? "SUCCEDED" : "FAILED");
    rt.getRobotTrajectoryMsg(trajectory);
    plan.trajectory_=trajectory;

but it didnt work too. Am I using it the wrong way ?? Please help me ,I've been puzzling over this question for days. I am truly very grateful for your help. !!

**Comment by simonschmeisser** [comment]
Typically you need to set acceleration limits in `joint_limits.yaml` to get realistic accelerations. You can compare the `time_from_start` of your trajectory (by using `rostopic echo /joint_trajectory_action/goal` (use tab completion to find the actual name of the topic) with the time it actually takes for the robot to move. If the robot takes a lot longer to move than calculated then you have some issue with the driver. If the times somewhat match but are too long you will need to increase the acceleration limit (the default is `1/s`)

**Comment by AtariaLee** [comment]
but I didn't set the  limits in `joint_limits.yaml`,
```
joint_limits:
  joint_1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
```

**Comment by simonschmeisser** [comment]
Not setting it means the default of `1/s` is used, which is slow. Try something in the range of 5 to 20. Unfortunately manufacturers do not provide the actual limits (and they are load and posture dependent) so you have to experiment a bit

**Comment by AtariaLee** [comment]
thanks, i will try it tomorrow.
and Is that code correct ?
```

moveit::planning_interface::MoveGroupInterface::Plan plan;

robot_trajectory::RobotTrajectory rt(arm.getCurrentState()->getRobotModel(),"manipulator");

rt.setRobotTrajectoryMsg(*arm.getCurrentState(),trajectory);
trajectory_processing::IterativeParabolicTimeParameterization iptp;
bool ItSuccess = iptp.computeTimeStamps(rt);
ROS_INFO("Computed time stamp %s", ItSuccess ? "SUCCEDED" : "FAILED");
rt.getRobotTrajectoryMsg(trajectory);
plan.trajectory_=trajectory;

```

**Comment by AtariaLee** [comment]
After i tried to change joint limits ,like
```
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 13.0543
    has_acceleration_limits: true
    max_acceleration: 3
  joint_2:
    has_velocity_limits: true
    max_velocity: 13.0543
    has_acceleration_limits: true
    max_acceleration: 3
  joint_3:
    has_velocity_limits: true
    max_velocity: 13.0543
    has_acceleration_limits: true
    max_acceleration: 3
  joint_4:
    has_velocity_limits: true
    max_velocity: 14.3633
    has_acceleration_limits: true
    max_acceleration: 3
  joint_5:
    has_velocity_limits: true
    max_velocity: 14.3633
    has_acceleration_limits: true
    max_acceleration: 3
  joint_6:
    has_velocity_limits: true
    max_velocity: 16.1959
    has_acceleration_limits: true
    max_acceleration: 3
```

Then came a warning    `Joint velocity-limits unspecified.  Using default velocity-ratio.`.
im confused that I had set the limit, why does the screen show an unspecified limit value?
So ,how could i set  `joint the velocity-limits`?
