### ISSUE TITLE
# Issues with Moveit Servoing when running with Universal Robots ROS Driver on E series 

### ISSUE THREAD

**Issue by Mohatashem** [ros-planning/moveit#3153]
Hello,

I've been trying to implement moveit_servo with the Universal Robots ROS driver for a UR10e robot. I was able to run the `/servo_server` node and publish to `servo_server/delta_twist_cmds` topic as well as run the `pose_tracking_example` file successfully with a gazebo simulation. 

However, I run into issues with implementation of `pose_tracking_example` on the real robot. 
## Steps followed:
1. Launching the bringup file
2. Launching the moveit_planning_execution launch file
3. Swithcing from trajectory controller to joint group position controller
4. Launching the pose_tracking launch file

## Behaviour:
- Pose tracking node seems to publish to `servo_server/target_pose`. In the video (visualization of the real robot), the moving frame is the target_pose. 

https://user-images.githubusercontent.com/40743268/171396092-f7dd77c7-2a39-4f07-8d6e-27cded110162.mp4

The code is the same as pose_tracking_example.cpp. the only changes I made are that there is an offset in z direction and then the target pose is decremented in the z-direction as well.

- However, the robot does not move at all. The terminal displays a `target control rate missed` and exits the program.

`rostopic echo /servo_server/delta_twist_cmds` shows zero values on all `/servo_server/delta_twist_cmds/twist/linear/...` and `.../angular`

## Details:
Here is the rqt_graph and as far as I've understood, everything seems to be connected:

![rosgraph_moveit_servo](https://user-images.githubusercontent.com/40743268/171393709-abc11dfd-cf8b-4ca0-b6a3-937bc1300eb9.png)

Here is what I have so far:
1. The robot config yaml file:

``` 
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment
command_in_type: "speed_units" # "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/
scale:
    rotational:  0.3 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
    joint: 0.01
low_pass_filter_coeff: 2.  # Larger --> trust the filtered data more, trust the measurements less.

publish_period: 0.002 # 1/Nominal publish rate [seconds]
low_latency_mode:  false #false #false # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

command_out_type: std_msgs/Float64MultiArray 

publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false


move_group_name:  wall_arm 
planning_frame: wall_arm_base_link 


ee_frame_name: wall_arm_tool0   
robot_link_command_frame:  wall_arm_tool0 

incoming_command_timeout:  0.1
num_outgoing_halt_msgs_to_publish: 4


lower_singularity_threshold:  17  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 30 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.


cartesian_command_in_topic: delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: joint_states
status_topic: status # Publish status to this topic
command_out_topic: /wall_arm/joint_group_pos_controller/command 


check_collisions: false # true # Check collisions?
collision_check_rate: 40 # [Hz] Collision-checking can easily bog down a CPU if done too often.

collision_check_type:  threshold_distance #threshold_distance
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.05 # 0.05 # Start decelerating when a scene collision is this far [m]
collision_distance_safety_factor: 1000 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.001 # Stop if a collision is closer than this [m]
```

2. PID params for pose tracking:

```
windup_limit: 0.05

# PID gains
x_proportional_gain: 1.5 
y_proportional_gain: 1.5 
z_proportional_gain: 1.5 
x_integral_gain: 0.0
y_integral_gain: 0.0
z_integral_gain: 0.0
x_derivative_gain: 0.0
y_derivative_gain: 0.0
z_derivative_gain: 0.0

angular_proportional_gain: 0.5 
angular_integral_gain: 0.0
angular_derivative_gain: 0.0

```

3. Terminal output when launching pose tracking example:

```
... logging to /home/pp1744/.ros/log/feae6ca2-e01a-11ec-a6d0-a0291986156e/roslaunch-pp1744-Precision-5550-11989.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://pp1744-Precision-5550:42233/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /servo_server/parameter_ns: servo_server
 * /servo_server/servo_server/angular_derivative_gain: 0.0
 * /servo_server/servo_server/angular_integral_gain: 0.0
 * /servo_server/servo_server/angular_proportional_gain: 0.5
 * /servo_server/servo_server/cartesian_command_in_topic: delta_twist_cmds
 * /servo_server/servo_server/check_collisions: False
 * /servo_server/servo_server/collision_check_rate: 40
 * /servo_server/servo_server/collision_check_type: threshold_distance
 * /servo_server/servo_server/collision_distance_safety_factor: 1000
 * /servo_server/servo_server/command_in_type: speed_units
 * /servo_server/servo_server/command_out_topic: /wall_arm/joint_g...
 * /servo_server/servo_server/command_out_type: std_msgs/Float64M...
 * /servo_server/servo_server/ee_frame_name: wall_arm_tool0
 * /servo_server/servo_server/hard_stop_singularity_threshold: 30
 * /servo_server/servo_server/incoming_command_timeout: 0.1
 * /servo_server/servo_server/joint_command_in_topic: delta_joint_cmds
 * /servo_server/servo_server/joint_limit_margin: 0.1
 * /servo_server/servo_server/joint_topic: joint_states
 * /servo_server/servo_server/low_latency_mode: False
 * /servo_server/servo_server/low_pass_filter_coeff: 2.0
 * /servo_server/servo_server/lower_singularity_threshold: 17
 * /servo_server/servo_server/min_allowable_collision_distance: 0.001
 * /servo_server/servo_server/move_group_name: wall_arm
 * /servo_server/servo_server/num_outgoing_halt_msgs_to_publish: 4
 * /servo_server/servo_server/planning_frame: wall_arm_base_link
 * /servo_server/servo_server/publish_joint_accelerations: False
 * /servo_server/servo_server/publish_joint_positions: True
 * /servo_server/servo_server/publish_joint_velocities: False
 * /servo_server/servo_server/publish_period: 0.008
 * /servo_server/servo_server/robot_link_command_frame: wall_arm_tool0
 * /servo_server/servo_server/scale/joint: 0.01
 * /servo_server/servo_server/scale/linear: 0.6
 * /servo_server/servo_server/scale/rotational: 0.3
 * /servo_server/servo_server/scene_collision_proximity_threshold: 0.05
 * /servo_server/servo_server/self_collision_proximity_threshold: 0.01
 * /servo_server/servo_server/status_topic: status
 * /servo_server/servo_server/use_gazebo: False
 * /servo_server/servo_server/windup_limit: 0.05
 * /servo_server/servo_server/x_derivative_gain: 0.0
 * /servo_server/servo_server/x_integral_gain: 0.0
 * /servo_server/servo_server/x_proportional_gain: 1.5
 * /servo_server/servo_server/y_derivative_gain: 0.0
 * /servo_server/servo_server/y_integral_gain: 0.0
 * /servo_server/servo_server/y_proportional_gain: 1.5
 * /servo_server/servo_server/z_derivative_gain: 0.0
 * /servo_server/servo_server/z_integral_gain: 0.0
 * /servo_server/servo_server/z_proportional_gain: 1.5

NODES
  /
    servo_server (zerog_moveit_servo/pose_tracking_example)

ROS_MASTER_URI=http://localhost:11311

process[servo_server-1]: started with pid [12013]
[ INFO] [1653917663.781682605] [/servo_server] [ros.moveit_core.robot_model]: Loading robot model 'zerog'...
[ INFO] [1653917663.782410623] [/servo_server] [ros.moveit_core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1653917667.711158390] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Starting planning scene monitor
[ INFO] [1653917667.712774088] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Listening to '/planning_scene'
[ INFO] [1653917667.712793934] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1653917667.714130366] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Listening to '/collision_object'
[ INFO] [1653917667.715539130] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1653917667.718427493] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[ WARN] [1653917668.044454951] [/servo_server] [ros.moveit_servo.servo_calcs]: An acceleration limit is not defined for this joint; minimum stop distance should not be used for collision checking
[ WARN] [1653917668.049594692] [/servo_server] [ros.moveit_servo.pose_tracking]: Target control rate was missed
[ INFO] [1653917668.052517787] [/servo_server] [ros.zerog_moveit_servo.pose_tracking_example]: Servo status: No warnings
[ INFO] [1653917678.064269919] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Stopping world geometry monitor
[ INFO] [1653917678.064670070] [/servo_server] [ros.moveit_ros_planning.planning_scene_monitor]: Stopping planning scene monitor
[servo_server-1] process has finished cleanly
log file: /home/pp1744/.ros/log/feae6ca2-e01a-11ec-a6d0-a0291986156e/servo_server-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

I am not sure what to do next. Just for additional information, I tried running the servo_server node directly and published to `servo_server/delta_twist_cmds` directly via `rqt_ez_publisher`. In this situation, the robot seems to move albeit in a slow, jerky manner.

Any suggestions how to proceed from here?

Any help is really appreciated. I've been stuck at it for quite a while.
