### ISSUE TITLE
master/noetic-devel moveit.rosinstall

### ISSUE THREAD

**Issue by vanem** [ros-planning/moveit#3191]
While following the Moveit! "Gettin started" here https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html I've noticed that in
`https://github.com/ros-planning/moveit/blob/noetic-devel/moveit.rosinstall`
The entry:
```
- git:
    local-name: panda_moveit_config
    uri: https://github.com/ros-planning/panda_moveit_config.git
    version: melodic-devel
```
points to melodic-devel branch, not on the existing noetic-devel branch, which exists and seems to diverge by quite a lot of commits. Is this an oversight or a deliberate choice?
The "Getting started" instructions for noetic also require explicitely cloning the melodic-devel branch for panda config:
`git clone https://github.com/ros-planning/panda_moveit_config.git -b melodic-devel`
Again, is there a reason for this apparent inconsistency?
