### ISSUE TITLE
Octomap detect arm as obstacle 

### ISSUE THREAD

**Issue by adamanov** [ros-planning/moveit#3210]
Hello, 

I am performing a simple pick and placement pipeline like in tutorial, for a detecting, and picking the box.
The box is added to the planning scene to be able to deactivate collision checking between the gripper and the box as expected. 

And as you can see, the box is also removed from octomap, after that perform execution of caclulated trajectory. 

![Screenshot from 2022-09-07 16-01-58](https://user-images.githubusercontent.com/53511072/188900435-2b47271e-f7e6-4d9b-a066-6db2b9ee5669.png)
![stack_position](https://user-images.githubusercontent.com/53511072/188902146-cbb1c731-dc07-4c56-8c88-84d8e2ff87b1.png)

However, when the robot arm apper into camera view, the octamap detected the arm as obstacle, and the arm stops. 

I tried both plugings `DepthImageOctomapUpdater` and `PointCloudOctomapUpdater` but the results is same. 

```
sensors:
  # - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   image_topic: /jackal/front_realsense/depth/image_rect_raw
  #   queue_size: 1                      # The number of images to queue up.
  #   near_clipping_plane_distance: 0.01 # The minimum distance before lack of visibility. (meters)
  #   far_clipping_plane_distance: 1.0   # The maximum distance before lack of visibility.
  #   shadow_threshold: 0.2              # The minimum brightness of the shadow map below an entity for its dynamic shadow to be visible
  #   padding_scale: 5.0                 # Should always be >= 1.0. Scale up collision shapes in the scene before excluding them from the octomap. 
  #   padding_offset: 0.03               # Absolute padding (in m) around scaled collision shapes when excluding them from the octomap.
  #   max_update_rate: 1.0
  #   point_subsample: 122
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /jackal/front_realsense/depth/color/points
    max_range: 0.7
    point_subsample: 122
    padding_offset: 0.03
    padding_scale: 1.1
    max_update_rate: 5.0
    filtered_cloud_topic: filtered_realsense_cloud
````
How can I remove the arm as collision object? I guess self collision does not work properly.
