### ISSUE TITLE
Execution delay issue with move_group execute method

### ISSUE THREAD

**Issue by ConradLiuuu** [ros-planning/moveit#3304]
Hi Everyone, 

As title mentioned, I use **move_group execute** method to execute a planned trajectory. 
The trajectory is expected to take 2 seconds from position A to position B.
However, the real situation is it took about 2.8 even 3 seconds to finish execution.

Here are parts of the program
```cpp
moveit::planning_interface::MoveGroupInterface::Plan plan = ...; // assign a planned trajectory

auto t1 = ros::Time::now();
move_group->execute(plan);
auto t2 = ros::Time::now();

cout << "execution time: " << (t2 - t1).toSec() << endl;
``` 

Could you tell me how to solve this issue and what is the point makes this issue?

Thank you

**Comment by rhaschke** [comment]
Your robot is not capable to accelerate or move as fast as MoveIt assumes. Adjust max velocity and acceleration parameters to tell MoveIt about your robot's capabilities!

**Comment by ConradLiuuu** [comment]
Hi rhaschke, 

Thank you for your reply!

I edited **max_velocity** and **max_acceleration** in joint_limits.yaml. 
This file is located in a package which is created by MoveIt Setup Assistant
Current parameters are 100, previous parameters are 3.14

But it didn't work, I still encountered execution delay issue.

Did I edit a wrong file or wrong parameters?

Here is joint_limits.yaml detail
```
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
  joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
  joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
  joint_4:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
  joint_5:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
  joint_6:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: true
    max_acceleration: 100
```

**Comment by rhaschke** [comment]
So you even increased the limits! You need to decrease them because your robot is slower than expected...

**Comment by ConradLiuuu** [comment]
Hi rhaschke,

Thanks for your advisement!

I edited max_velocity and max_acceleration from 3.14 to 1.5 but it did not work.

Even I set **has_velocity_limits** and **has_acceleration_limits** to false, the situation is the same.

Maybe I misunderstood your advisement, could you describe the solution more detail?

Thank you

**Comment by rhaschke** [comment]
`has_*_limits` should be true. Otherwise, the limit will be ignored completely.
Reducing the limits should have an effect. Try to reduce even more, say to 0.1 to validate that the new values are considered.
You can check that the values are actually used by calling python's `RobotInterface::get_joint_limits(joint_name)`.
Note that you cannot change those values dynamically. They have to be set on the parameter server before starting any node (e.g. move_group) using them.

**Comment by ConradLiuuu** [comment]
Hi rhaschke,

I tried to set `max_velocity` and `max_acceleration` to 0.1, also set `has_velocity_limits` and `has_acceleration_limits` to true.
Before I ran `move_group` node, I also checked values of `has_*_limits` and `max_*` by rosparam command, they are correct values.

However robot motion is slower than I expected. (I expect the motion took 3 seconds to finish, but it took 3.4 seconds)

Here are parameters I set
```
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
  joint_6:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
```
