### ISSUE TITLE
Hz is constant at 10hz while using moveit servoing

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3353]
Hi, I am using [pose_tracking_example.cpp](https://github.com/ros-planning/moveit/blob/master/moveit_ros/moveit_servo/src/cpp_interface_example/pose_tracking_example.cpp) as a template to follow aruco marker with XArm. When I am checking on the hz rate of the topic `/xarm/xarm6_traj_controller/command` it is operating at 10Hz only, causing a lot of latency in my robot. When I use [XARM_Servoing](https://github.com/xArm-Developer/xarm_ros/tree/master/xarm_moveit_servo) example it works at approximately 40Hz. I am not sure as config file is same only difference is that example does use velocity command and not use multi-threading. 
Is it possible that there are some parameters that are causing this 

```
// Run the pose tracking in a new thread
  std::thread move_to_pose_thread(
      [&tracker, &lin_tol, &rot_tol] { tracker.moveToPose(lin_tol, rot_tol, 0.1 /* target pose timeout */);});
 
```

```
subscribed to [/xarm/xarm6_traj_controller/command]
average rate: 10.000
	min: 0.100s max: 0.100s std dev: 0.00003s window: 10

```
I tried the following steps as suggested to reduce the latency 

1. Modify xarm_controller/config/xarm6_controllers.yaml (note that the 6-axis is used as an example), and appropriately increase the update_rate (100?)
2. Modify xarm_moveit_servo/config/xarm_moveit_servo_config.yaml, increase publish_period appropriately (0.1?), set low_latency_mode to true
3. Modify report type to true in xarm_ros/xarm6_moveit_config/launch/realMove_exec.launch  `<arg name="report_type" default="dev" />	`

My `config.yaml `looks like 

```

###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.4  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.8 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 0.5

## Properties of outgoing commands
publish_period: 0.1  # 1/Nominal publish rate [seconds]
low_latency_mode: true  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray or trajectory_msgs/JointTrajectory
command_out_type: trajectory_msgs/JointTrajectory

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## Incoming Joint State properties
low_pass_filter_coeff: 2.0  # Larger --> trust the filtered data more, trust the measurements less.

## MoveIt properties
move_group_name:  xarm6   # rewrite by robot dof
planning_frame: link_base  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: link_eef  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  link_eef  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  0.2  # Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  50.0  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 50.0 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: servo_server/delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: servo_server/delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: servo_server/status # Publish status to this topic
command_out_topic: /xarm/xarm6_traj_controller/command # rewrite by robot dof

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 10.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.02 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000.0 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]
```

`
CODE SNIPPET`

  ```
// Run the pose tracking in a new thread
  std::thread move_to_pose_thread(
      [&tracker, &lin_tol, &rot_tol] { tracker.moveToPose(lin_tol, rot_tol, 0.1 /* target pose timeout */);});
 

  ros::Rate loop_rate(10); // time delay in HZ (10HZ=100ms)
  while(ros::ok())

  {  std_msgs::Float64MultiArray val = listener.aruco_data;

  if (!val.data.empty()) {

    // Modify the pose target a little bit each cycle
    // This is a dynamic pose target

    // This was the error for the arm to stop intermittently
    // target_pose.pose.position.z = current_ee_tf.transform.translation.z;

    // std::cout << "Current position in z is  " << target_pose.pose.position.z << std::endl;
    target_pose.pose.position.x = val.data.at(0);
    // target_pose.pose.position.y = val.data.at(1);
    target_pose.pose.position.z = val.data.at(2);

    // std::cout << "direct value achieved" << std::endl;
    // std::cout << "without down resetTargetPose" << std::endl;

    // std::cout << "No Sleep" << std::endl; // it jerk at a position with no sleep

    target_pose.header.stamp = ros::Time::now();
    target_pose_pub.publish(target_pose);
    tracker.resetTargetPose();
    loop_rate.sleep();

   
  }
  else{
    std::cout << "data is not received" << std::endl;
    loop_rate.sleep();
  }}
```

ANY HELP WOULD BE MUCH APPRECIATED
