### ISSUE TITLE
moveit_servo servo_server Node not Outputting Anything to command_out_topic

### ISSUE THREAD

**Issue by jnnanni** [ros-planning/moveit#3366]
### Description

I am unable to get the servo_server node to output to my specified command_out_topic. I am trying to publish to a JointGroupPositionController. ```rostopic info``` claims that the servo_server node is in fact a publisher of the command topic, but when I attempt to send delta twist commands via ```rostopic pub``` nothing happens. I have tried multiple different combinations of twist commands both linear and angular to no avail. The terminal output from the servo_server node does not seem to reveal any type of error and the node continues running. I am hoping this is simply an issue of user error but I am confused as to why there are no obvious errors being output.

### Your environment

* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Binary build 1.1.11-1focal.20230306.114555

### Steps to reproduce

While I am unsure if this is simply a setup issue or if something is truly wrong with the configuration on my end, I would love if other people could attempt to recreate the issue on their end using the code in my repo.

1. [This](https://github.com/umrover/mrover-ros/tree/bl/2023-servo) is the git repo for our project, the moveit package can be found [here](https://github.com/umrover/mrover-ros/tree/bl/2023-servo/src/teleop/mrover_arm) in the repo
2. Build the mrover and mrover_arm packages alongside eachother in one catkin workspace.
3. Run ```roslaunch mrover arm_gazebo_sim.launch``` in one terminal
4. In another terminal, run ```roslaunch mrover_arm servo.launch```
5. Attempt to use ```rostopic pub /servo_server/delta_twists_cmds```

### Expected behaviour

Servo_server should output Float64MultiArray messages to the /gazebo_arm_controller/command topic

### Actual behaviour

Servo_server does not output anything

### Backtrace or Console output

[servo_server node output](https://gist.github.com/jnnanni/a3c53ae44ad65513fe0d76cd831c8d93)

<details>
<summary>rostopic info output</summary>
<br>

``` bash
joe@joe-Yoga-7-15ITL5:~/Desktop/mrover_catkin_ws/src/mrover$ rostopic info /gazebo_arm_controller/command 
Type: std_msgs/Float64MultiArray

Publishers: 
 * /mrover_arm_follow_joint_trajectory (http://joe-Yoga-7-15ITL5:46407/)
 * /servo_server (http://joe-Yoga-7-15ITL5:34883/)

Subscribers: 
 * /gazebo (http://joe-Yoga-7-15ITL5:38009/)
```

</details>

<details>
<summary>simulated_config.yaml content</summary>
<br>

``` yaml
###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: true # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.6  # Max linear velocity. Meters per publish_period. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.3 # Max angular velocity. Rads per publish_period. Unit is [rad/s]. Only used for Cartesian commands.
  # Max joint angular/linear velocity. Rads or Meters per publish period. Only used for joint commands on joint_command_in_topic.
  joint: 0.01
low_pass_filter_coeff: 2.  # Larger --> trust the filtered data more, trust the measurements less.

## Properties of outgoing commands
publish_period: 0.008  # 1/Nominal publish rate [seconds]
low_latency_mode: false  # Set this to true to publish as soon as an incoming Twist command is received (publish_period is ignored)

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray (for ros_control JointGroupVelocityController or JointGroupPositionController)
# or trajectory_msgs/JointTrajectory (for Universal Robots and other non-ros_control robots)
command_out_type: std_msgs/Float64MultiArray

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## MoveIt properties
move_group_name:  Arm  # Often 'manipulator' or 'arm'
planning_frame: world  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: hand  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  base_link  # commands must be given in the frame of a robot link. Usually either the base or end effector

## Stopping behaviour
incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  17  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 30 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: joint_states
status_topic: status # Publish status to this topic
command_out_topic: /gazebo_arm_controller/command # Publish outgoing commands here

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 50 # [Hz] Collision-checking can easily bog down a CPU if done too often.
# Two collision check algorithms are available:
# "threshold_distance" begins slowing down when nearer than a specified distance. Good if you want to tune collision thresholds manually.
# "stop_distance" stops if a collision is nearer than the worst-case stopping distance and the distance is decreasing. Requires joint acceleration limits
collision_check_type: threshold_distance
# Parameters for "threshold_distance"-type collision checking
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.05 # Start decelerating when a scene collision is this far [m]
# Parameters for "stop_distance"-type collision checking
collision_distance_safety_factor: 1000 # Must be >= 1. A large safety factor is recommended to account for latency
min_allowable_collision_distance: 0.01 # Stop if a collision is closer than this [m]
```

</details>
