### ISSUE TITLE
Non optimal motions using move_group.set_pose_target()

### ISSUE THREAD

**Issue by thve25** [ros-planning/moveit#3497]
### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* I tried both Source (master) and Binary (1.1.13-2focal.20230801.171807)
* 6 DOF arm

### Description

Using `move_group.set_pose_target(pose)`, Sometimes, I'm getting weird IK joint angles* and weird motions.
Using `move_group.set_joint_value_target(pose,True)`, I'm ***not*** getting weird motions.

_*= When I check the final joint angles (plan[1].joint_trajectory.points[-1].positions) of the plan=move_group.plan() in these cases, the joint angles are a valid IK solution, but far from the most optimal one. When I calculate an IK solution using roboticstoolbox, and use MotionPlanning in Rviz ( with collision aware IK) and the joint angels set to the IK solution i'm getting decent motions as intended._

However, obstacle avoidance is only supported using `set_pose_target()`, because it plans in Cartesian space.

How can I get the best of both worlds, ie. efficient motions and obstacle avoidance?

### I tried:

 - increasing planning attempts: `move_group.set_num_planning_attempts(20)`
   - didn't work
 - increase tolerance: `move_group.set_goal_tolerance(0.01)`
   - weird motions occurred less often.
  - KDLKinematicsPlugin and TRAC_IKKinematicsPlugin
  - Different planners (e.g. BiTRRT, RRT, FMT, etc)
  - Different pipelines (OMPL, OMPL-CHOMP)

###  ompl_planning.yaml:
```
planner_configs:
 BiTRRT:
    type: geometric::BiTRRT
    range: 0.0 
    temp_change_factor: 0.1  
    init_temperature: 100  
    frountier_threshold: 0.0  
    frountier_node_ratio: 0.1  
    cost_threshold: 1e300  
 etc

manipulator:
  default_planner_config: BiTRRT
  planner_configs:
    - BiTRRT
    - etc
  projection_evaluator: joints(joint_1,joint_2)
  longest_valid_segment_fraction: 0.005
```
