### ISSUE TITLE
Pilz: No IK solver available for link error with bio_ik

### ISSUE THREAD

**Issue by captain-yoshi** [ros-planning/moveit#3566]
I can't use `bio_ik` with Pilz. With Trac-IK all is good. You can see my configuration below. Will have to investigate...maybe something is wrong with bio_ik.
```bash
[ERROR] [1707343231.030526630]: No IK solver available for link: "robotiq_2f140_tcp"
```

It is failling on the `jmg->canSetStateFromIK`. The lm->getName() is respectively `ur3_wrist_3_link` for both bio_ik and trac_ik. 
```cpp
  const auto* lm = robot_state.getRigidlyConnectedParentLinkModel(pos_constraint.link_name, nullptr, jmg);
  ROS_ERROR_STREAM("lm name = " << lm->getName());

  if (!lm || !jmg->canSetStateFromIK(lm->getName()))
  {
    std::ostringstream os;
    os << "No IK solver available for link: \"" << pos_constraint.link_name << "\"";
    throw NoIKSolverAvailable(os.str());
  }

```
---
kinematics.yaml
```yaml
eef_gripper:
   # KDL
   #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
   #kinematics_solver_search_resolution: 0.005
   #kinematics_solver_timeout: 0.005

   # Trac-IK
   # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
   # kinematics_solver_search_resolution: 0.005
   # kinematics_solver_timeout: 0.005

   # BioIK
   kinematics_solver: bio_ik/BioIKKinematicsPlugin
   kinematics_solver_search_resolution: 0.005
   kinematics_solver_timeout: 0.005
   kinematics_solver_attempts: 1
```
SRDF
```xml
    <group name="eef_gripper">
        <chain base_link="ur3_base_link" tip_link="robotiq_2f140_tcp"/>
    </group>
    
    <end_effector name="gripper" parent_link="robotiq_2f140_tcp" group="gripper" parent_group="eef_gripper"/>
```
